theme: jekyll-theme-slate
title: David Chiu
description: Associate Professor, Computer Science
institution: University of Puget Sound
office: Thompson Hall 303
email: dchiu@pugetsound.edu
kramdown:
  syntax_highlighter_opts:
    disable: true
