theme: jekyll-theme-slate
title: David Chiu
description: Associate Professor
description2: Computer Science
institution: University of Puget Sound
office: Thompson Hall 303
email: <a href="mailto:dchiu@pugetsound.edu">dchiu@pugetsound.edu</a>
