import java.util.Queue;

/**
 * Do not edit this file.
 *
 * @author David
 */
public interface Syntax
{    
    /**
     * Checks whether the tags in the HTML string are properly nested.
     * 
     * This method uses a stack to match opening and closing tags in the correct order.
     * Void tags (e.g., <br/>) and comments (<!-- ... -->) are ignored.
     * 
     * @return true if all opening tags are matched with correct closing tags in the proper order;
     *         false if any tag is mismatched, extra, or missing.
     */
    boolean isProperlyNested();
    
    /**
     * Suggests minimal fixes for improperly nested tags.
     * Returns a queue of tags (and inserted corrections) representing a fixed version.
     */
    Queue<String> suggestFixes();
    
    /**
     * Prints tags with indentation based on nesting level.
     */
    void prettyPrint();
}